(async function(){
const output=document.querySelector('#results'),results=[];
const source=await Promise.all(['order-payment-orders-sync-v102.js','paid-order-result-card-v104.js'].map(n=>fetch('../../public/leaip0/assets/frontend/js/core/'+n).then(r=>r.text())));
const assert=(v,m)=>{if(!v)throw Error(m)};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function setup(orders,{cards=[],pending=null,failRead=false,list=false}={}){
 const f=document.createElement('iframe');f.hidden=true;document.body.append(f);const w=f.contentWindow,d=w.document;let stored=JSON.stringify(orders),writes=0;const timers=[];
 Object.defineProperty(w,'localStorage',{value:{getItem(){if(failRead)throw Error('test storage unavailable');return stored},setItem(k,v){stored=v;writes++}}});
 w.__lxState={pendingOrderProduct:pending};
 w.setTimeout=(fn,delay)=>{timers.push({fn,delay,cancelled:false});return timers.length};w.clearTimeout=id=>{if(timers[id-1])timers[id-1].cancelled=true};
 d.body.innerHTML=cards.map(id=>`<button class="lx-payment-confirm-reco" data-open-payment-confirm ${id===null?'':`data-lx-order-id="${id}"`}><span class="answer-cta-title">待支付订单</span></button>`).join('')+'<button id="pay" data-occ-pay-confirm>测试触发</button>'+(list?'<div class="lx-orders-wrap"><div class="ohead"><span class="cnt">保留原数量</span></div>'+orders.map(o=>`<div class="ord"><button data-order-detail="${o.orderId}"></button><span class="nm"></span><div class="amt"></div><span class="ost"></span><div class="mid"></div></div>`).join('')+'</div>':'');
 source.forEach(s=>w.eval(s));d.dispatchEvent(new w.Event('DOMContentLoaded'));await wait(0);
 return {w,d,timers,get orders(){return JSON.parse(stored)},get writes(){return writes},set orders(v){stored=JSON.stringify(v)},run(delay){const t=timers.find(t=>!t.cancelled&&t.delay===delay);if(t){t.cancelled=true;t.fn()}},click(){d.querySelector('#pay').click()},remove(){f.remove()}};
}
async function test(name,fn){try{await fn();results.push({name,pass:true})}catch(e){results.push({name,pass:false,error:e.message})}output.textContent=JSON.stringify(results,null,2)}
for(const status of ['pending','unpaid','cancelled','refunded'])await test('启动不改写 '+status,async()=>{const t=await setup([{orderId:'TEST-A',status,price:100}],{cards:['TEST-A'],list:true});t.run(600);t.run(24);assert(t.writes===0,'startup wrote orders');assert(t.orders[0].status===status,'status changed');assert(!t.d.querySelector('[data-lx-order-status="paid"]'),'card falsely paid');assert(!t.d.querySelector('.ost').textContent.includes('已支付'),'list falsely paid');t.remove()});
await test('空订单与存储读取失败',async()=>{for(const failRead of [false,true]){const t=await setup([],{failRead});t.run(600);t.run(24);assert(t.writes===0,'unexpected write');t.remove()}});
await test('其他订单已支付不升级待付款卡与无身份历史卡',async()=>{const t=await setup([{orderId:'TEST-A',status:'paid'}],{cards:['TEST-B',null]});assert(!t.d.querySelector('[data-lx-order-status="paid"]'),'unrelated card upgraded');t.remove()});
await test('仅对应订单升级，兼容旧 paidAt',async()=>{const t=await setup([{orderId:'TEST-A',paidAt:'2026-08-31 12:00:00'}],{cards:['TEST-A','TEST-B']});assert(t.d.querySelector('[data-lx-order-id="TEST-A"]').dataset.lxOrderStatus==='paid','matching not paid');assert(!t.d.querySelector('[data-lx-order-id="TEST-B"]').dataset.lxOrderStatus,'other changed');t.remove()});
await test('明确未支付状态优先于旧 paidAt',async()=>{const t=await setup([{orderId:'TEST-A',status:'unpaid',paidAt:'old'}],{cards:['TEST-A']});assert(!t.d.querySelector('[data-lx-order-status]'),'unpaid treated as paid');t.remove()});
await test('只有点击没有成功记录不写入',async()=>{const t=await setup([{orderId:'TEST-A',status:'pending'}],{pending:{_pendingOrderNo:'TEST-A',price:0}});t.click();for(const delay of [50,350,900,1600])t.run(delay);assert(t.writes===0,'click inferred success');t.remove()});
await test('未知订单号不回退第一笔',async()=>{const t=await setup([{orderId:'TEST-A',status:'paid'}],{pending:{_pendingOrderNo:'TEST-UNKNOWN',price:0}});t.click();t.run(1600);assert(t.writes===0,'unknown id wrote first order');t.remove()});
await test('成功后只补全对应订单，零金额保留，重复同步幂等',async()=>{const first={orderId:'TEST-OTHER',status:'pending',price:999};const t=await setup([first],{pending:{_pendingOrderNo:'TEST-A',price:0,payable:0,originalPrice:100,items:[{name:'测试商品',sku:'TEST-SKU',configurationLabel:'测试配置'}]},cards:['TEST-A','TEST-OTHER']});t.click();t.orders=[first,{orderId:'TEST-A',price:0,paidAt:'2026-08-31 12:00:00'}];t.run(1600);await wait(0);assert(JSON.stringify(t.orders[0])===JSON.stringify(first),'other order changed');assert(t.orders[1].paidAmount===0,'zero replaced');assert(t.orders[1].configurationLabel==='测试配置','config lost');const n=t.writes;t.run(900);assert(t.writes===n,'repeat wrote same order');assert(t.d.querySelector('[data-lx-order-id="TEST-A"]').dataset.lxOrderStatus==='paid','window event missed');t.remove()});
await test('跨标签页 storage 事件同步卡片',async()=>{const t=await setup([],{cards:['TEST-A']});t.orders=[{orderId:'TEST-A',status:'paid'}];t.w.dispatchEvent(new t.w.StorageEvent('storage',{key:'lexiang.orders.v1'}));assert(t.d.querySelector('[data-lx-order-status="paid"]'),'storage event missed');t.remove()});
await test('重复渲染不再产生 DOM 写入且不覆盖订单中心数量',async()=>{const t=await setup([{orderId:'TEST-A',status:'paid',name:'测试商品',price:10}],{list:true});t.run(600);t.run(24);await wait(0);let mutations=0;const obs=new t.w.MutationObserver(r=>mutations+=r.length);obs.observe(t.d.querySelector('.lx-orders-wrap'),{childList:true,subtree:true,attributes:true,characterData:true});t.run(24);await wait(0);assert(mutations===0,'repeat DOM mutations '+mutations);assert(t.d.querySelector('.cnt').textContent==='保留原数量','count overwritten');obs.disconnect();t.remove()});
output.textContent=JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,results},null,2);document.title=results.every(r=>r.pass)?'PASS P0 订单隔离回归':'FAIL P0 订单隔离回归';
})();
